<?php

/**
 * Description of regioni
 *
 * @author borcha
 */
class regioni {

    public static $jmbg = array(
        array(//broj registra  [0]
            '00',
            '01',
            '02',
            '03',
            '04',
            '05',
            '06',
            '07',
            '08',
            '09',
            '10',
            '11',
            '12',
            '13',
            '14',
            '14',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
            '22',
            '23',
            '24',
            '25',
            '26',
            '27',
            '28',
            '29',
            '30',
            '31',
            '32',
            '33',
            '34',
            '35',
            '36',
            '37',
            '38',
            '39',
            '40',
            '41',
            '42',
            '43',
            '44',
            '45',
            '46',
            '47',
            '48',
            '49',
            '50',
            '60',
            '61',
            '62',
            '63',
            '64',
            '65',
            '66',
            '67',
            '68',
            '69',
            '70',
            '71',
            '72',
            '73',
            '74',
            '75',
            '76',
            '77',
            '78',
            '79',
            '80',
            '81',
            '82',
            '83',
            '84',
            '85',
            '86',
            '87',
            '88',
            '89',
            '90',
            '91',
            '92',
            '93',
            '94',
            '95',
            '96',
            '97',
            '98',
            '99'),
        array(//region [1]
            'Stranci-mesana upotreba',
            'stranci u BIH',
            'Stranci u CG',
            'Stranci u HR',
            'Stranci u Makedoniji',
            'Stranci u Sloveniji',
            'Ne koristi se',
            'Stranci u Uzoj Srbiji',
            'Stranci u Vojvodini',
            'Stranci na Kosovu i Metohiji',
            'Banja Luka',
            'Bihac',
            'Doboj',
            'Gorazde',
            'Livno',
            'Mostar',
            'Prijedor',
            'Sarajevo',
            'Tuzla',
            'Zenica',
            'Ne koristi se',
            'Podgorica',
            'Bar Ulcinj',
            'Budva,Kotor i Tivat',
            'Herceg Novi',
            'Cetinje',
            'Niksic',
            'Berane,Rozaje,Plav i Andrijevica',
            'Bjelo polje, Mojkovac',
            'Pljevlja, Zabljak',
            'Osijek',
            'Bjelovar,Virovitica,Koprivnica i Pakrac',
            'Varazdin, Medjumurje',
            'Zagreb',
            'Karlovac',
            'Lika',
            'Istra, Primorje',
            'Sisak, Banovina',
            'Dalmacija',
            'Nije u upotrebi',
            'Ne koristi se',
            'Bitolj',
            'Kumanovo',
            'Ohrid',
            'Prilep',
            'Skoplje',
            'Strumica',
            'Tetovo',
            'Veles',
            'Stip',
            'Slovenija',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Privremen boravak',
            'Ne koristi se',
            'Beograd',
            'Kragujevac, Jagodina',
            'Nis,Pirot,Toplica',
            'Leskovac, Vranje',
            'Zajecar, Bor',
            'Smederevo, Pozarevac',
            'Macva, Kolubara',
            'Kraljevo, Krusevac',
            'Uzice',
            'Novi Sad',
            'Sombor',
            'Subotica',
            'Vrbas',
            'Kikinda',
            'Zrenjanin',
            'Pancevo',
            'Vrsac',
            'Ruma',
            'Sremska Mitrovica',
            'Ne koristi se',
            'Pristina',
            'Kosovska Mitrovica',
            'Pec',
            'Djakovica',
            'Prizren',
            'Gnjilane',
            'Ne postoji',
            'Ne postoji',
            'Ne postoji"'),
        array(//rebulika  [2]
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'Stranci',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'BIH',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Crna Gora',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Hrvatska',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Makedonija',
            'Slovenija',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Privremeno',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Uza Srbija',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Vojvodina',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo',
            'Kosovo')
    );

}
